In [1]:
import torch
from tqdm import tqdm
from model import seedformer_dim128
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import Dataset,DataLoader
import open3d as o3d
import os
from pytorch3d.loss import chamfer_distance
import numpy as np
import gc
#torch.cuda.empty_cache()
#gc.collect()
from torch.optim.lr_scheduler import StepLR
import utils.utils as utils

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
#utils.correct_bbox_label(bbox)

### Dataset and Dataloader

https://pytorch.org/tutorials/beginner/basics/data_tutorial.html
https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

In [2]:
class RacingDataset(Dataset):
    def __init__(self,root_dir,target_points=4731):
        self.root_dir = root_dir
        self.file_list = os.listdir(root_dir)
        self.filter_file_list = self.filter_list()
        self.target_points = target_points

    def __len__(self):
        return len(self.filter_file_list)

    def __getitem__(self,index):
        pcd_path = os.path.join(self.root_dir,self.filter_file_list[index])
        pcd = o3d.io.read_point_cloud(pcd_path)

        points = torch.tensor(pcd.points, dtype=torch.float32)
        #padded_points = self.pad_point_cloud(pcd.points)

        return points,pcd_path

    #def pad_point_cloud(self, points):
    #    num_points = len(points)
    #    if num_points < self.target_points:
    #        # Pad the point cloud with zeros to match the target size
    #        padded_points = torch.cat([torch.tensor(points), torch.zeros(self.target_points - num_points, 3)])
    #    else:
    #        padded_points = torch.tensor(points)
    #    return padded_points
    
    def filter_list(self):
        '''
        Filter the inputs so that only pcds with more than 50 points are included in the training
        :return:
        '''
        filtered_list=[]
        for filename in self.file_list:
            pcd = o3d.io.read_point_cloud(os.path.join(self.root_dir,filename))
            points = torch.tensor(pcd.points, dtype=torch.float32)
            if len(points)>=0:
                filtered_list.append(filename)
        return filtered_list
   


In [3]:
#pcd_pad=o3d.io.read_point_cloud("/home/omar/TUM/Data/cropped/sim/018840.pcd")
#pcd_pad_tens=torch.tensor(pcd_pad.points,dtype=torch.float32)
#print(pcd_pad_tens[0])

In [4]:
def collate_fn(batch):
    # Define the target number of points for padding
    target_num_points = 4731
    
    # Pad each point cloud to have target_num_points points
    padded_points_batch = []
    for points, _ in batch:
        num_points_to_pad = target_num_points - points.size(0)
        if num_points_to_pad > 0:
            pad = torch.zeros(num_points_to_pad, 3, dtype=torch.float32)
            padded_points = torch.cat((points, pad), dim=0)
        else:
            padded_points = points[:target_num_points]  # Trim to target_num_points if exceeds
        padded_points_batch.append(padded_points)
    
    padded_points = pad_sequence(padded_points_batch, batch_first=True, padding_value=0)
    
    paths = [item[1] for item in batch]
    
    return padded_points, paths
# Load the largest point cloud
pcd_pad = o3d.io.read_point_cloud("/home/omar/TUM/Data/cropped/sim/018840.pcd")
pcd_pad_tens = torch.tensor(pcd_pad.points, dtype=torch.float32)

# Create the dataset and dataloader
dataset = RacingDataset(root_dir="/home/omar/TUM/Data/cropped/real", target_points=len(pcd_pad_tens))
dataloader = DataLoader(dataset, batch_size=8, shuffle=True, num_workers=8, collate_fn=collate_fn)

print(len(dataloader))
print(dataloader.dataset)

/tmp/ipykernel_157392/800869091.py:23: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:261.)
  pcd_pad_tens = torch.tensor(pcd_pad.points, dtype=torch.float32)


750


In [ ]:
#from numba import cuda
# 
#cuda.select_device(0) # choosing second GPU 
#cuda.close()

In [ ]:
torch.manual_seed(42)
#del model
model=seedformer_dim128(up_factors=[1, 2, 2])
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
model.to(device)
epochs=100
optimizer=torch.optim.Adam(model.parameters(),lr=0.001, weight_decay=5e-4)
scheduler = StepLR(optimizer, step_size=30, gamma=0.1)  # Reduce LR by a factor of 0.1 every 30 epochs

for epoch in range(epochs):
    running_loss=0
    # Wrap the DataLoader with tqdm to track progress
    with tqdm(enumerate(dataloader, 0), total=len(dataloader), desc=f'Epoch {epoch+1}/{epochs}', unit='batch') as pbar:
        for i, data in pbar:
            inputs, labels = data
            inputs = inputs.to(device)  # Move data to GPU if available

            optimizer.zero_grad()
            outputs = model(inputs)
            losses = []

            for input_pc, output_pc in zip(inputs, outputs):
                # Calculate Chamfer Distance loss using pytorch3d.loss.chamfer_distance
                loss, _ = chamfer_distance(input_pc.unsqueeze(0), output_pc.unsqueeze(0))
                losses.append(loss)

            loss = torch.mean(torch.stack(losses))
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            pbar.set_postfix(loss=running_loss / (i + 1))  # Update tqdm progress bar with the current loss
        scheduler.step()  # Step the learning rate scheduler

    print(f'Epoch {epoch+1} Loss: {running_loss / len(dataloader)}')  # Log the epoch loss

print('Finished Training')


In [ ]:
#model=None

In [5]:
def apply_and_save_res(dataset,dataloader,model,savedir):
    model.eval()
    # Apply the model and visualize differences
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.eval()
    
    for dataset, dataloader,  in [(dataset, dataloader)]:
        for i, data in enumerate(tqdm(dataloader, unit='point cloud')):
            #if i >= num_samples:
            #    break
            
            inputs, paths = data
            #print(paths)
            inputs = inputs.to(device)
    
            with torch.no_grad():
                outputs = model(inputs)
    
            outputs_cpu = outputs.cpu().numpy()

        #for path, output in zip(paths, outputs_cpu):
            filename = os.path.basename(paths[0])
            output_pcd = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(outputs_cpu[0]))
            f_name = os.path.join(savedir, filename)
            o3d.io.write_point_cloud(f_name, output_pcd)


## Save The Data


In [6]:
simulation_dataset = RacingDataset(root_dir="/home/omar/TUM/Data/cropped/sim")
simulation_dataloader = DataLoader(simulation_dataset, batch_size=1, shuffle=True, num_workers=8,collate_fn=collate_fn)

# Load real dataset
real_dataset = RacingDataset(root_dir="/home/omar/TUM/Data/cropped/real")
real_dataloader = DataLoader(real_dataset, batch_size=1, shuffle=True, num_workers=8,collate_fn=collate_fn)
apply_and_save_res(dataset=real_dataset,dataloader=real_dataloader,model=model,savedir="/home/omar/TUM/Data/reconstructed_cropped/real")

NameError: name 'model' is not defined

## "Stitch" the data

In [15]:
def crop_invert_stitch(original_pcd,car_reconstructed,bbox_coords):
    orientation_angle = float(bbox_coords[-1])
    # print(orientation_angle)
    h, w, l = bbox_coords[8:11]
    rotation_mat_z = np.array([
        [np.cos(orientation_angle), -np.sin(orientation_angle), 0.0],
        [np.sin(orientation_angle), np.cos(orientation_angle), 0.0],
        [0.0, 0.0, 1.0]
    ])
    center = bbox_coords[11:14]
    bbox = o3d.geometry.OrientedBoundingBox(center=center, R=rotation_mat_z, extent=[l, w, h])
   # orignal_crop_invert =o3d.geometry.PointCloud.crop(original_pcd,bbox)
    inliers_indices = bbox.get_point_indices_within_bounding_box(original_pcd.points)
        
    inliers_pcd = original_pcd.select_by_index(inliers_indices, invert=False) # select inside points = cropped 
    outliers_pcd = original_pcd.select_by_index(inliers_indices, invert=True) #select outside points
    stitched_pcd=outliers_pcd+car_reconstructed

    return stitched_pcd

## Create and save the new dataset

# Correcting Labels


In [5]:
labels_folder="/home/omar/TUM/data_MA/m1695833/Sim2RealDistributionAlignedDataset/sim/data/label/"
save_folder="/home/omar/TUM/Data/SeedFormer_2602_npy/sim/labels/"
for label in os.listdir(labels_folder):
    file = open(labels_folder+label)
    bbox=file.read()
    bbox_correct=utils.correct_bbox_label(bbox)
    file.close()
    file_write=open(save_folder+label,"w+")
    file_write.write(" ".join(bbox_correct))
    file_write.close()
    print(bbox_correct)
    #print(items)

['86.13', '2.08', '0.59', '4.88', '1.9', '1.18', '0.01', 'Car']
['-36.92', '-5.76', '0.59', '4.88', '1.9', '1.18', '-0.01', 'Car']
['42.03', '0.86', '0.59', '4.88', '1.9', '1.18', '-0.0', 'Car']
['-0.46', '-5.79', '0.6', '4.88', '1.9', '1.18', '-0.01', 'Car']
['93.19', '19.5', '4.5', '4.88', '1.9', '1.18', '0.4', 'Car']
['-44.16', '3.35', '0.95', '4.88', '1.9', '1.18', '-0.11', 'Car']
['75.86', '4.29', '0.91', '4.88', '1.9', '1.18', '0.08', 'Car']
['-34.94', '-3.96', '0.76', '4.88', '1.9', '1.18', '-0.08', 'Car']
['-24.56', '-3.99', '0.96', '4.88', '1.9', '1.18', '-0.12', 'Car']
['59.57', '8.24', '2.19', '4.88', '1.9', '1.18', '0.27', 'Car']
['44.82', '4.99', '1.61', '4.88', '1.9', '1.18', '0.2', 'Car']
['-64.58', '5.08', '1.05', '4.88', '1.9', '1.18', '-0.14', 'Car']
['-30.6', '-4.01', '0.82', '4.88', '1.9', '1.18', '-0.12', 'Car']
['38.49', '6.41', '1.3', '4.88', '1.9', '1.18', '0.22', 'Car']
['2.69', '-5.91', '0.59', '4.88', '1.9', '1.18', '0.01', 'Car']
['98.06', '3.84', '1.83', '4

In [78]:
reconstructed_car_path="/home/omar/TUM/Data/combined/sim/"
#bbox_path="/home/omar/TUM/data_MA/m1695833/Sim2RealDistributionAlignedDataset/sim/data/label"

#original_sim_path="/home/omar/TUM/data_MA/m1695833/Sim2RealDistributionAlignedDataset/sim/data/pcl/"
original_sim_path="/home/omar/TUM/Data/reconstructed_scene/sim/"
#reconstructed_scene_path="/home/omar/TUM/Data/reconstructed_scene/sim/"
npy_final_path="/home/omar/TUM/Data/SeedFormer_2602_npy_zyx/reconstructed/points/"
file_car_list=[]
for filename_car in os.listdir(reconstructed_car_path):
    file_car_list.append(filename_car)
    txt=filename_car.replace('.pcd',".txt")
   # bbox = (open(bbox_path+"/"+txt, "r")).read().split()
    original_pcd = o3d.io.read_point_cloud(original_sim_path+filename_car)
    filename_=filename_car.split(".")[0]
    #if  (int)(filename_)<=24995:#<>
        
        #print(filename_)
    np_array=np.asarray(original_pcd.points)#.pcd
    #arr2d=np.asarray(pcd_sim.points)
    x=np_array.copy()[:,0]
    np_array[:,0]=np_array[:,2]
    np_array[:,2]=x
    np.save(npy_final_path+filename_,np_array)#.npy

    #reconstructed_car= o3d.io.read_point_cloud(reconstructed_car_path +"/"+ filename_car)
    #crop_invert=crop_invert_stitch(original_pcd,reconstructed_car, bbox)
    #o3d.io.write_point_cloud(reconstructed_scene_path+"/"+filename_car,crop_invert)
    #np_array=np.asarray(crop_invert.points)
    #np.save(npy_final_path+filename_car,np_array)
#



In [14]:
#source_label_path = "/home/omar/TUM/Masterarbeit/Data/m1695833/Sim2RealDistributionAlignedDataset/real/data/label/"
#pcd_real=o3d.io.read_point_cloud("/home/omar/TUM/Data/cropped/sim/018840.pcd")
#pcd_sim=o3d.io.read_point_cloud("/home/omar/TUM/Data/reconstructed_scene/sim/018845.pcd")
#arr=np.asarray(pcd_sim.points)
#print(pcd_sim.points)
#print("np shape: " ,np.asarray(pcd_sim.points).shape)
#arr2d=np.asarray(pcd_sim.points)
#x=arr2d.copy()[:,0]
#arr2d[:,0]=arr2d[:,2]
#arr2d[:,2]=x
#pcd = o3d.geometry.PointCloud()
#pcd.points = o3d.utility.Vector3dVector(arr2d)
#o3d.io.write_point_cloud("/home/omar/TUM/Data/sync.pcd", pcd)
#
## Load saved point cloud and visualize it
#pcd_load = o3d.io.read_point_cloud("/home/omar/TUM/Data/sync.pcd")
##o3d.visualization.draw_geometries([pcd_load])
#pcd_car_recons=o3d.io.read_point_cloud("/home/omar/TUM/Data/reconstructed_cropped/sim/020000.pcd")
#pcl=o3d.io.read_point_cloud("/home/omar/TUM/Data/SeedFormer_2602_npy_zyx/real/points/018840.npy")
pcl=np.load("/home/omar/TUM/Data/SeedFormer_2602_npy/sim/points/015500.npy")
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(pcl)
#box=["Car" ,0.0, 0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,1.18, 1.9 ,4.88 ,1.56 ,6.55 ,1.01 ,-0.0]
box=["Car" ,0.0, 0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,1.18, 1.9 ,4.88 ,76.79 ,1.53,0.96 ,0.06]

#pcd_cut=crop_invert_stitch(pcl,box)
#pcd=pcd_cut+pcd_car_recons
utils.visualize(pcl=pcd,bbox_coordinates=box)
#utils.visualize(pcl=pcd_sim)
#
#utils.visualize(pcl=pcd_sim)
#
#utils.visualize(pcl=pcl)
#
#utils.visualize(pcl=pcd)

[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] [SimpleShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] [PhongShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] Shader error: 
[Open3D WARNING] [NormalShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] Shader error: 
[Open3D WARNING] [SimpleBlackShaderForPointCloudNormal] Compiling shaders failed.
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] Shader error: 
[Open3D WARNING] [PhongShaderForTriangleMesh] Compiling shaders failed.
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] [SimpleShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] [SimpleShaderForPointCloud] Something is wrong in compiling 

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



KeyboardInterrupt: 

In [15]:
pcl=np.load("/home/omar/TUM/Data/SeedFormer_2602_npy/reconstructed/points/015500.npy")
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(pcl)
#box=["Car" ,0.0, 0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,1.18, 1.9 ,4.88 ,1.56 ,6.55 ,1.01 ,-0.0]
box=["Car" ,0.0, 0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,1.18, 1.9 ,4.88 ,76.79 ,1.53,3.96 ,0.06]

#pcd_cut=crop_invert_stitch(pcl,box)
#pcd=pcd_cut+pcd_car_recons
utils.visualize(pcl=pcd,bbox_coordinates=box)
#utils.visualize(pcl=pcd_sim)

[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] [SimpleShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] [PhongShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] Shader error: 
[Open3D WARNING] [NormalShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] Shader error: 
[Open3D WARNING] [SimpleBlackShaderForPointCloudNormal] Compiling shaders failed.
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] Shader error: 
[Open3D WARNING] [PhongShaderForTriangleMesh] Compiling shaders failed.
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] GLFW Error: The GLFW library is not initialized
[Open3D WARNING] [SimpleShaderForPointCloud] Compiling shaders failed.
[Open3D WARNING] [SimpleShaderForPointCloud] Something is wrong in compiling 

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



KeyboardInterrupt: 

In [53]:
array2d=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
print("array2d : ",array2d)
print("array2d shape " , array2d.shape)
print("-------------")
#print("transpose : " ,array2d.T)
#print("reshape:  " ,array2d.reshape(-1).T)
x=array2d.copy()[:,0]
print("x col : " ,array2d[:,0])

print("z col : " ,array2d[:,2])
array2d[:,0]=array2d[:,2]
print("x",x)
array2d[:,2]=x
print("x col  after swap: " ,array2d)

array2d :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array2d shape  (4, 3)
-------------
x col :  [ 1  4  7 10]
z col :  [ 3  6  9 12]
x [ 1  4  7 10]
x col  after swap:  [[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


In [ ]:
# Load simulation dataset
simulation_dataset = RacingDataset(root_dir="/home/omar/TUM/Data/cropped/sim")
simulation_dataloader = DataLoader(simulation_dataset, batch_size=1, shuffle=True, num_workers=8,collate_fn=collate_fn)

# Load real dataset
real_dataset = RacingDataset(root_dir="/home/omar/TUM/Data/cropped/real")
real_dataloader = DataLoader(real_dataset, batch_size=1, shuffle=True, num_workers=8,collate_fn=collate_fn)

# Select a subset of samples
num_samples = 3

# Apply the model and visualize differences
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.eval()

for dataset, dataloader, name in [(simulation_dataset, simulation_dataloader, "Simulation"), 
                                  (real_dataset, real_dataloader, "Real")]:
    for i, data in enumerate(tqdm(dataloader, desc=f'Processing {name} dataset', unit='point cloud')):
        if i >= num_samples:
            break
        
        inputs, paths = data
        #print(paths)
        inputs = inputs.to(device)

        with torch.no_grad():
            outputs = model(inputs)

        original_pc = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(inputs.squeeze().cpu().numpy()))
        original_pc.paint_uniform_color([1, 0, 0])  # Paint original point cloud in red

        reconstructed_pc = o3d.geometry.PointCloud(o3d.utility.Vector3dVector(outputs.squeeze().cpu().numpy()))
        reconstructed_pc.paint_uniform_color([0, 1, 0])  # Paint reconstructed point cloud in green

        o3d.visualization.draw_geometries([original_pc, reconstructed_pc], window_name=f"{name} - Sample {i+1}")
#model=None

In [ ]:
# Notes#
'''
input threshold adjust - 
'''